command_timeout = 200

[username]
format = " [╭─$user]($style)@"
show_always = true
style_root = "bold green"
style_user = "bold green"

[hostname]
disabled = false
format = "[$hostname]($style) in "
ssh_only = false
style = "bold dimmed green"
trim_at = "-"

[directory]
style = "cyan"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "repo: "

[sudo]
disabled = false

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
deleted = "x"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
style = "white"

[cmd_duration]
disabled = false
format = "took [$duration]($style)"
min_time = 1

[character]
error_symbol = " [╰─❯](bold red)"
success_symbol = " [╰─❯](bold green)"